"""empty message

Revision ID: 56b536d15256
Revises: 1b38ea4bb317
Create Date: 2015-09-27 00:56:44.186958

"""

# revision identifiers, used by Alembic.
revision = '56b536d15256'
down_revision = '1b38ea4bb317'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    ### end Alembic commands ###
